name: Vienna

on: pull_request

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Build Xcode project
      run: xcodebuild -project Vienna.xcodeproj -scheme Vienna -configuration Development build-for-testing | xcpretty && exit ${PIPESTATUS[0]}
    - name: Test Xcode project
      run: xcodebuild -project Vienna.xcodeproj -scheme Vienna -configuration Development test | xcpretty && exit ${PIPESTATUS[0]}
