name: Vienna

on: pull_request

jobs:
  test:
    name: Test
    runs-on: macos-11

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Build Xcode project
      run: xcodebuild -project Vienna.xcodeproj -scheme Vienna -configuration Development build-for-testing
    - name: Test Xcode project
      run: xcodebuild -project Vienna.xcodeproj -scheme Vienna -configuration Development test
	  timeout-minutes: 15
